name: Fake CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  fake-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Simulate build/test
        run: |
          echo "Starting fake CI..."
          sleep 1   # wait 1 second
          echo "Fake CI passed!"
