name: Merge back

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  call-release-workflow:
    #uses: syrocolab/workflows/.github/workflows/merge-back.yml@main
    uses: ./.github/workflows/shared-workflows-merge-back.yml
    with:
      source-branch: main
      target-branch: develop
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
