name: Merge back

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-back:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

      - name: Check if back-merge PR already exists
        id: check_pr
        run: |
          PR_COUNT=$(gh pr list \
            --base develop \
            --head main \
            --state open \
            --json number \
            --jq 'length')

          echo "count=$PR_COUNT" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

      - name: Create PR
        id: create-pr
        if: steps.check_pr.outputs.count == '0'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          branch: back-merge/main-to-develop
          base: develop
          title: "chore(release): merge back "
          body: "Merge back"

      - name: Enable auto-merge
        if: steps.check_pr.outputs.count == '0' && steps.create-pr.outputs.pull-request-number != ''
        run: |
          gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
