name: Release
run-name: >-
  ${{ 
    contains(github.event.head_commit.message, 'chore(main): release') 
    && 'Create tag and release' 
    || 'Create changelog and version bump PR' 
  }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  call-release-workflow:
    #uses: syrocolab/workflows/.github/workflows/release.yml@main
    uses: ./.github/workflows/shared-workflows-release.yml
    with:
      target-branch: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
