name: Release automerge
run-name: Automerge release changelog PR

on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-release-changelog-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Automerge release changelog PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
