name: Release
run-name: |
  ${{ (github.event_name == 'push' && (contains(github.event.head_commit.message, 'Merge pull request ') == true || contains(github.event.head_commit.message, 'chore(release') == true)) 
    && 'Create release PR' 
    || 'Prepare release changelog and version bump' 
  }}

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  call-release-workflow:
    #uses: syrocolab/workflows/.github/workflows/release.yml@main
    uses: ./.github/workflows/shared-workflows-release.yml
    with:
      target-branch: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

  use-output:
    runs-on: ubuntu-latest
    needs: call-release-workflow
    if: needs.call-release-workflow.outputs.pr_url && needs.call-release-workflow.outputs.tag_name
    steps:
      - name: Use the outputs
        run: |
          echo "PR URL: ${{ needs.call-release-workflow.outputs.pr_url }}"
          echo "Tag Name: ${{ needs.call-release-workflow.outputs.tag_name }}"

      - name: Notify Slack
        uses: slackapi/slack-github-action@v3
        continue-on-error: true
        env:
          PR_URL: ${{ needs.call-release-workflow.outputs.pr_url }}
          VERSION: ${{ needs.call-release-workflow.outputs.tag_name }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "NodeJS API ${{ env.VERSION }} (release)"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Release PR is ready:\n<${{ env.PR_URL }}|chore(release): nodejs API ${{ env.VERSION }}>"
                  },
                }
              ]
            }
