name: Release automerge

on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Auto-merge if CI passed
        uses: pascalgn/automerge-action@v0.15.3
        with:
          github_token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          merge_method: squash
          labels: |
            autorelease
