name: Release
run-name: >-
  ${{ 
    contains(github.event.head_commit.message, 'chore(main): release') 
    && 'Create tag and release' 
    || 'Create changelog and version bump PR' 
  }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  call-release-workflow:
    #uses: syrocolab/workflows/.github/workflows/release.yml@main
    uses: ./.github/workflows/shared-workflows-release.yml
    with:
      target-branch: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

  call-merge-back-workflow:
    needs: call-release-workflow
    if: needs.call-release-workflow.outputs.release_created == 'true'
    #uses: syrocolab/workflows/.github/workflows/merge-back.yml@main
    uses: ./.github/workflows/shared-workflows-merge-back.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      source-branch: main
      target-branch: develop
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

  slack-notification-pr:
    runs-on: ubuntu-latest
    needs: call-release-workflow
    if: needs.call-release-workflow.outputs.release_created != 'true'
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v3
        continue-on-error: true
        env:
          PR_URL: ${{ needs.call-release-workflow.outputs.html_url }}
          VERSION: ${{ needs.call-release-workflow.outputs.tag_name }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "NodeJS API ${{ env.VERSION }} (release)"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Release PR is ready:\n<${{ env.PR_URL }}|chore(release): nodejs API ${{ env.VERSION }}>"
                  },
                },
              ]
            }

  slack-notification-release:
    runs-on: ubuntu-latest
    needs: call-release-workflow
    if: needs.call-release-workflow.outputs.release_created == 'true'
    steps:
      - name: Format Release Body for Slack
        id: slack_format
        run: |
          CHANGELOG="${{ steps.release.outputs.body }}"

          # Convert Headers (###) to Bold
          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/^###+ (.*)/*\1*/g')

          # Convert GFM Bold (**text**) to Slack Bold (*text*)
          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/\*\*([^*]+)\*\//*\1*/g')

          # Convert leading "*" bullets to "-"
          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/^\* / - /g')

          # Remove commit links: " ([hash](url))" 
          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/ \(\[[0-9a-f]+\]\(https?:\/\/[^)]+\)\)//g')

          # Escape specific characters for JSON (optional but safer)
          CHANGELOG=$(echo "$CHANGELOG" | jq -aRs .)

          echo "formatted_body=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Notify Slack
        uses: slackapi/slack-github-action@v3
        continue-on-error: true
        env:
          PR_URL: ${{ needs.call-release-workflow.outputs.html_url }}
          VERSION: ${{ needs.call-release-workflow.outputs.tag_name }}
          CHANGELOG: ${{ steps.slack_format.outputs.changelog }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":package: Backend <${{ env.PR_URL }}|${{ env.VERSION }}>\n${{ env.CHANGELOG}}"
                  },
                },
              ]
            }
