name: Release start
run-name: Start a new release from develop branch

on:
  workflow_dispatch:

jobs:
  call-release-start-workflow:
    #uses: syrocolab/workflows/.github/workflows/release-start.yml@main
    uses: ./.github/workflows/shared-workflows-release-start.yml
    permissions:
      contents: write
    with:
      source-branch: develop
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
