name: Release start
run-name: Start a new release from develop branch

on:
  workflow_dispatch:

jobs:
  call-release-start-workflow:
    #uses: syrocolab/workflows/.github/workflows/release-start.yml@main
    uses: ./.github/workflows/shared-workflows-release-start.yml
    permissions:
      contents: write
    with:
      source-branch: develop
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

  use-output:
    runs-on: ubuntu-latest
    needs: call-release-start-workflow
    if: needs.call-release-start-workflow.outputs.pr_url && needs.call-release-start-workflow.outputs.tag_name
    steps:
      - name: Use the outputs
        run: |
          echo "PR URL: ${{ needs.call-release-start-workflow.outputs.pr_url }}"
          echo "Tag Name: ${{ needs.call-release-start-workflow.outputs.tag_name }}"

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_URL: ${{ needs.call-release-start-workflow.outputs.pr_url }}
          VERSION: ${{ needs.call-release-start-workflow.outputs.tag_name }}
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "NodeJS API ${{ env.VERSION }} (release)"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Release PR is ready:\n<${{ env.PR_URL }}|chore(deploy): nodejs API ${{ env.VERSION }}>"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Review PR"
                    },
                    "url": "${{ env.PR_URL }}"
                  }
                }
              ]
            }
