name: Shared workflows - Release

on:
  workflow_call:
    secrets:
      token:
        description: "Token"
        required: true
    inputs:
      target-branch:
        description: "Target branch"
        required: true
        type: string
    outputs:
      release_created:
        description: "Whether a release PR was created"
        value: ${{ jobs.release-please.outputs.release_created }}
      body:
        description: "Created PR body"
        value: ${{ jobs.release-please.outputs.body }}
      tag_name:
        description: "Created tag name"
        value: ${{ jobs.release-please.outputs.tag_name }}
      html_url:
        description: "Created PR URL"
        value: ${{ jobs.release-please.outputs.html_url }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      body: ${{ steps.release.outputs.body }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      html_url: ${{ steps.release.outputs.html_url }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.token }}
          target-branch: ${{ inputs.target-branch }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
