name: Shared workflows - Release start

on:
  workflow_call:
    secrets:
      token:
        description: "Token"
        required: true
    inputs:
      source-branch:
        description: "Source branch to create release branch from"
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head ${{ inputs.source-branch }} \
            --title "chore: release ${{ inputs.source-branch }} to main" \
            --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
